name: achievement_app
description: A new Flutter application to track achievements.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^9.1.3
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/background_logo.png 
